version: '3.8'

services:
  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    # networks:
    #   - my-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=fullstack
      - MONGO_HOST=mongodb
    # networks:
    #   - my-network

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask-app
    # networks:
    #   - my-network

# networks:
#     my-network:
#   default:
#     driver: bridge